from PIL import Image
from colors import colorsDict
from traitEncodings import TRAIT_ENCODINGS

def drawSuit(im, primaryColor, primaryColorShade, tieColor):
    imNew = Image.new('RGBA', (24, 24), (0, 0, 0, 0))

    imNew.putpixel((6, 19), colorsDict["black"])
    imNew.putpixel((7, 19), primaryColor)
    imNew.putpixel((8, 19), primaryColor)

    imNew.putpixel((5, 20), colorsDict["black"])
    imNew.putpixel((6, 20), primaryColorShade)
    imNew.putpixel((7, 20), colorsDict["black"])
    imNew.putpixel((8, 20), primaryColor)
    imNew.putpixel((9, 20), colorsDict["black"])
    imNew.putpixel((10, 20), colorsDict["white"])
    imNew.putpixel((11, 20), tieColor)
    imNew.putpixel((12, 20), colorsDict["white"])
    imNew.putpixel((13, 20), colorsDict["black"])
    imNew.putpixel((14, 20), primaryColor)
    imNew.putpixel((15, 20), colorsDict["black"])

    imNew.putpixel((4, 21), colorsDict["black"])
    imNew.putpixel((5, 21), primaryColorShade)
    imNew.putpixel((6, 21), primaryColor)
    imNew.putpixel((7, 21), primaryColor)
    imNew.putpixel((8, 21), colorsDict["black"])
    imNew.putpixel((9, 21), colorsDict["black"])
    imNew.putpixel((10, 21), colorsDict["white"])
    imNew.putpixel((11, 21), tieColor)
    imNew.putpixel((12, 21), colorsDict["white"])
    imNew.putpixel((13, 21), primaryColor)
    imNew.putpixel((14, 21), colorsDict["black"])
    imNew.putpixel((15, 21), colorsDict["black"])

    imNew.putpixel((3, 22), colorsDict["black"])
    imNew.putpixel((4, 22), primaryColorShade)
    imNew.putpixel((5, 22), primaryColor)
    imNew.putpixel((6, 22), primaryColor)
    imNew.putpixel((7, 22), primaryColor)
    imNew.putpixel((8, 22), primaryColor)
    imNew.putpixel((9, 22), primaryColor)
    imNew.putpixel((10, 22), colorsDict["white"])
    imNew.putpixel((11, 22), colorsDict["white"])
    imNew.putpixel((12, 22), colorsDict["white"])
    imNew.putpixel((13, 22), primaryColor)
    imNew.putpixel((14, 22), primaryColor)
 
    imNew.putpixel((2, 23), colorsDict["black"])
    imNew.putpixel((3, 23), primaryColorShade)
    imNew.putpixel((4, 23), primaryColor)
    imNew.putpixel((5, 23), primaryColor)
    imNew.putpixel((6, 23), primaryColor)
    imNew.putpixel((7, 23), primaryColor)
    imNew.putpixel((8, 23), primaryColor)
    imNew.putpixel((9, 23), colorsDict["black"])
    imNew.putpixel((10, 23), primaryColor)
    imNew.putpixel((11, 23), primaryColor)
    imNew.putpixel((12, 23), colorsDict["black"])
    imNew.putpixel((13, 23), primaryColor)
    imNew.putpixel((14, 23), primaryColor)
    imNew.putpixel((15, 23), colorsDict["black"])

    im.paste(imNew, (0,0), mask=imNew)
