from PIL import Image
from colors import colorsDict
from traitEncodings import TRAIT_ENCODINGS

def drawEyes(im, trait, type):
    imNew = Image.new('RGBA', (24, 24), (0, 0, 0, 0))

    typePrimaryColor = "typeNormal"
    if type == "l":
        typePrimaryColor = "typeLight"
    elif type == "d":
        typePrimaryColor = "typeDark"
    elif type == "b":
        typePrimaryColor = "typeBrown"
    elif type == "r":
        typePrimaryColor = "typeDarkBrown"
    elif type == "k":
        typePrimaryColor = "typeBlack"
    elif type == "z":
        typePrimaryColor = "typeZombie"
    elif type == "s":
        typePrimaryColor = "typeSkeleton"
    elif type == "v":
        typePrimaryColor = "typeDevil"
    elif type == "a":
        typePrimaryColor = "typeAlien"
    elif type == "w":
        typePrimaryColor = "typeSnowy"
    elif type == "o":
        typePrimaryColor = "typeSolana12"

    decodedType = TRAIT_ENCODINGS["eyes"][trait]
    if decodedType == "Vipers":

        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["pvGreen"])
        imNew.putpixel((9, 11), colorsDict["pvYellow"])
        imNew.putpixel((10, 11), colorsDict["pvOrange"])
        imNew.putpixel((11, 11), colorsDict["pvRed"])
        imNew.putpixel((12, 11), colorsDict["pvRed"])
        imNew.putpixel((13, 11), colorsDict["pvRed"])
        imNew.putpixel((14, 11), colorsDict["pvOrange"])
        imNew.putpixel((15, 11), colorsDict["pvYellow"])
        imNew.putpixel((16, 11), colorsDict["pvGreen"])
        imNew.putpixel((17, 11), colorsDict["pvBlue"])

        imNew.putpixel((5, 12), colorsDict["black"])
        imNew.putpixel((6, 12), colorsDict["black"])
        imNew.putpixel((7, 12), colorsDict["pvBlue"])
        imNew.putpixel((8, 12), colorsDict["pvGreen"])
        imNew.putpixel((9, 12), colorsDict["pvYellow"])
        imNew.putpixel((10, 12), colorsDict["pvOrange"])
        imNew.putpixel((11, 12), colorsDict["pvRed"])
        imNew.putpixel((13, 12), colorsDict["pvRed"])
        imNew.putpixel((14, 12), colorsDict["pvOrange"])
        imNew.putpixel((15, 12), colorsDict["pvYellow"])
        imNew.putpixel((16, 12), colorsDict["pvGreen"])
        imNew.putpixel((17, 12), colorsDict["pvBlue"])

        imNew.putpixel((8, 13), colorsDict["pvGreen"])
        imNew.putpixel((9, 13), colorsDict["pvYellow"])
        imNew.putpixel((10, 13), colorsDict["pvOrange"])
        imNew.putpixel((11, 13), colorsDict["pvRed"])
        imNew.putpixel((13, 13), colorsDict["pvRed"])
        imNew.putpixel((14, 13), colorsDict["pvOrange"])
        imNew.putpixel((15, 13), colorsDict["pvYellow"])
        imNew.putpixel((16, 13), colorsDict["pvGreen"])

    elif decodedType == "Happy":
        imNew.putpixel((9, 11), colorsDict["black"])
        imNew.putpixel((14, 11), colorsDict["black"])

        imNew.putpixel((8, 12), colorsDict["black"])
        imNew.putpixel((9, 12), colorsDict[typePrimaryColor])
        imNew.putpixel((10, 12), colorsDict["black"])
        imNew.putpixel((13, 12), colorsDict["black"])
        imNew.putpixel((14, 12), colorsDict[typePrimaryColor])
        imNew.putpixel((15, 12), colorsDict["black"])

        imNew.putpixel((8, 13), colorsDict[typePrimaryColor])
        imNew.putpixel((9, 13), colorsDict[typePrimaryColor])
        imNew.putpixel((14, 13), colorsDict[typePrimaryColor])
        imNew.putpixel((15, 13), colorsDict[typePrimaryColor])
    elif decodedType == "BigShades":
        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["bigShades1"])
        imNew.putpixel((9, 11), colorsDict["bigShades1"])
        imNew.putpixel((10, 11), colorsDict["bigShades1"])
        imNew.putpixel((13, 11), colorsDict["bigShades1"])
        imNew.putpixel((14, 11), colorsDict["bigShades1"])
        imNew.putpixel((15, 11), colorsDict["bigShades1"])

        imNew.putpixel((6, 12), colorsDict["black"])
        imNew.putpixel((8, 12), colorsDict["bigShades2"])
        imNew.putpixel((9, 12), colorsDict["bigShades2"])
        imNew.putpixel((10, 12), colorsDict["bigShades2"])
        imNew.putpixel((13, 12), colorsDict["bigShades2"])
        imNew.putpixel((14, 12), colorsDict["bigShades2"])
        imNew.putpixel((15, 12), colorsDict["bigShades2"])

        imNew.putpixel((8, 13), colorsDict["bigShades3"])
        imNew.putpixel((9, 13), colorsDict["bigShades3"])
        imNew.putpixel((10, 13), colorsDict["bigShades3"])
        imNew.putpixel((13, 13), colorsDict["bigShades3"])
        imNew.putpixel((14, 13), colorsDict["bigShades3"])
        imNew.putpixel((15, 13), colorsDict["bigShades3"])
    elif decodedType == "Wink":
        imNew.putpixel((14, 12), colorsDict[typePrimaryColor])
        imNew.putpixel((15, 12), colorsDict[typePrimaryColor])
        imNew.putpixel((14, 13), colorsDict["black"])
        imNew.putpixel((15, 13), colorsDict["black"])
    elif decodedType == "Laughing":
        imNew.putpixel((9, 11), colorsDict["black"])
        imNew.putpixel((14, 11), colorsDict["black"])

        imNew.putpixel((8, 12), colorsDict[typePrimaryColor])
        imNew.putpixel((9, 12), colorsDict[typePrimaryColor])
        imNew.putpixel((10, 12), colorsDict["black"])
        imNew.putpixel((13, 12), colorsDict["black"])
        imNew.putpixel((14, 12), colorsDict[typePrimaryColor])
        imNew.putpixel((15, 12), colorsDict[typePrimaryColor])

        imNew.putpixel((9, 13), colorsDict["black"])
        imNew.putpixel((14, 13), colorsDict["black"])

        imNew.putpixel((8, 13), colorsDict[typePrimaryColor])
        imNew.putpixel((15, 13), colorsDict[typePrimaryColor])
    elif decodedType == "HippieGlasses":

        imNew.putpixel((8, 11), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((9, 11), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((14, 11), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((15, 11), colorsDict["hippieGlassesOutline"])

        imNew.putpixel((6, 12), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((7, 12), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((8, 12), colorsDict["hippieGlasses"])
        imNew.putpixel((9, 12), colorsDict["hippieGlasses"])
        imNew.putpixel((10, 12), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((11, 12), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((12, 12), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((13, 12), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((14, 12), colorsDict["hippieGlasses"])
        imNew.putpixel((15, 12), colorsDict["hippieGlasses"])
        imNew.putpixel((16, 12), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((17, 12), colorsDict["hippieGlassesOutline"])

        imNew.putpixel((5, 13), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((7, 13), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((8, 13), colorsDict["hippieGlasses"])
        imNew.putpixel((9, 13), colorsDict["hippieGlasses"])
        imNew.putpixel((10, 13), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((13, 13), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((14, 13), colorsDict["hippieGlasses"])
        imNew.putpixel((15, 13), colorsDict["hippieGlasses"])
        imNew.putpixel((16, 13), colorsDict["hippieGlassesOutline"])

        imNew.putpixel((8, 14), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((9, 14), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((14, 14), colorsDict["hippieGlassesOutline"])
        imNew.putpixel((15, 14), colorsDict["hippieGlassesOutline"])
    elif decodedType == "MatrixGlasses":

        imNew.putpixel((8, 11), colorsDict["matrixGlasses"])
        imNew.putpixel((9, 11), colorsDict["matrixGlassesShine"])
        imNew.putpixel((10, 11), colorsDict["matrixGlasses"])
        imNew.putpixel((13, 11), colorsDict["matrixGlasses"])
        imNew.putpixel((14, 11), colorsDict["matrixGlassesShine"])
        imNew.putpixel((15, 11), colorsDict["matrixGlasses"])

        imNew.putpixel((8, 12), colorsDict["matrixGlassesShine"])
        imNew.putpixel((9, 12), colorsDict["matrixGlasses"])
        imNew.putpixel((10, 12), colorsDict["matrixGlasses"])
        imNew.putpixel((11, 12), colorsDict["black"])
        imNew.putpixel((12, 12), colorsDict["black"])
        imNew.putpixel((13, 12), colorsDict["matrixGlassesShine"])
        imNew.putpixel((14, 12), colorsDict["matrixGlasses"])
        imNew.putpixel((15, 12), colorsDict["matrixGlasses"])

        imNew.putpixel((8, 13), colorsDict["matrixGlasses"])
        imNew.putpixel((9, 13), colorsDict["matrixGlasses"])
        imNew.putpixel((10, 13), colorsDict["matrixGlasses"])
        imNew.putpixel((13, 13), colorsDict["matrixGlasses"])
        imNew.putpixel((14, 13), colorsDict["matrixGlasses"])
        imNew.putpixel((15, 13), colorsDict["matrixGlasses"])
    elif decodedType == "DiamondVipers":

        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["diamondVipers5"])
        imNew.putpixel((9, 11), colorsDict["diamondVipers4"])
        imNew.putpixel((10, 11), colorsDict["diamondVipers3"])
        imNew.putpixel((11, 11), colorsDict["diamondVipers2"])
        imNew.putpixel((12, 11), colorsDict["diamondVipers1"])
        imNew.putpixel((13, 11), colorsDict["diamondVipers2"])
        imNew.putpixel((14, 11), colorsDict["diamondVipers3"])
        imNew.putpixel((15, 11), colorsDict["diamondVipers4"])
        imNew.putpixel((16, 11), colorsDict["diamondVipers5"])
        imNew.putpixel((17, 11), colorsDict["diamondVipers6"])

        imNew.putpixel((5, 12), colorsDict["black"])
        imNew.putpixel((6, 12), colorsDict["black"])
        imNew.putpixel((7, 12), colorsDict["diamondVipers6"])
        imNew.putpixel((8, 12), colorsDict["diamondVipers5"])
        imNew.putpixel((9, 12), colorsDict["diamondVipers4"])
        imNew.putpixel((10, 12), colorsDict["diamondVipers3"])
        imNew.putpixel((11, 12), colorsDict["diamondVipers2"])
        imNew.putpixel((12, 12), colorsDict["diamondVipers1"])
        imNew.putpixel((13, 12), colorsDict["diamondVipers2"])
        imNew.putpixel((14, 12), colorsDict["diamondVipers3"])
        imNew.putpixel((15, 12), colorsDict["diamondVipers4"])
        imNew.putpixel((16, 12), colorsDict["diamondVipers5"])
        imNew.putpixel((17, 12), colorsDict["diamondVipers6"])

        imNew.putpixel((8, 13), colorsDict["diamondVipers5"])
        imNew.putpixel((9, 13), colorsDict["diamondVipers4"])
        imNew.putpixel((10, 13), colorsDict["diamondVipers3"])
        imNew.putpixel((11, 13), colorsDict["diamondVipers2"])
        imNew.putpixel((13, 13), colorsDict["diamondVipers2"])
        imNew.putpixel((14, 13), colorsDict["diamondVipers3"])
        imNew.putpixel((15, 13), colorsDict["diamondVipers4"])
        imNew.putpixel((16, 13), colorsDict["diamondVipers5"])
    elif decodedType == "Neo":

        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["neo5"])
        imNew.putpixel((9, 11), colorsDict["neo4"])
        imNew.putpixel((10, 11), colorsDict["neo3"])
        imNew.putpixel((11, 11), colorsDict["neo2"])
        imNew.putpixel((12, 11), colorsDict["neo1"])
        imNew.putpixel((13, 11), colorsDict["neo2"])
        imNew.putpixel((14, 11), colorsDict["neo3"])
        imNew.putpixel((15, 11), colorsDict["neo4"])
        imNew.putpixel((16, 11), colorsDict["neo5"])
        imNew.putpixel((17, 11), colorsDict["neo6"])

        imNew.putpixel((5, 12), colorsDict["black"])
        imNew.putpixel((6, 12), colorsDict["black"])
        imNew.putpixel((7, 12), colorsDict["neo6"])
        imNew.putpixel((8, 12), colorsDict["neo5"])
        imNew.putpixel((9, 12), colorsDict["neo4"])
        imNew.putpixel((10, 12), colorsDict["neo3"])
        imNew.putpixel((11, 12), colorsDict["neo2"])
        imNew.putpixel((12, 12), colorsDict["neo1"])
        imNew.putpixel((13, 12), colorsDict["neo2"])
        imNew.putpixel((14, 12), colorsDict["neo3"])
        imNew.putpixel((15, 12), colorsDict["neo4"])
        imNew.putpixel((16, 12), colorsDict["neo5"])
        imNew.putpixel((17, 12), colorsDict["neo6"])

        imNew.putpixel((8, 13), colorsDict["neo5"])
        imNew.putpixel((9, 13), colorsDict["neo4"])
        imNew.putpixel((10, 13), colorsDict["neo3"])
        imNew.putpixel((11, 13), colorsDict["neo2"])
        imNew.putpixel((13, 13), colorsDict["neo2"])
        imNew.putpixel((14, 13), colorsDict["neo3"])
        imNew.putpixel((15, 13), colorsDict["neo4"])
        imNew.putpixel((16, 13), colorsDict["neo5"])
    elif decodedType == "GoldenVipers":

        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["goldenVipers2"])
        imNew.putpixel((9, 11), colorsDict["goldenVipers3"])
        imNew.putpixel((10, 11), colorsDict["goldenVipers4"])
        imNew.putpixel((11, 11), colorsDict["goldenVipers5"])
        imNew.putpixel((12, 11), colorsDict["goldenVipers6"])
        imNew.putpixel((13, 11), colorsDict["goldenVipers5"])
        imNew.putpixel((14, 11), colorsDict["goldenVipers4"])
        imNew.putpixel((15, 11), colorsDict["goldenVipers3"])
        imNew.putpixel((16, 11), colorsDict["goldenVipers2"])
        imNew.putpixel((17, 11), colorsDict["goldenVipers1"])

        imNew.putpixel((5, 12), colorsDict["black"])
        imNew.putpixel((6, 12), colorsDict["black"])
        imNew.putpixel((7, 12), colorsDict["goldenVipers1"])
        imNew.putpixel((8, 12), colorsDict["goldenVipers2"])
        imNew.putpixel((9, 12), colorsDict["goldenVipers3"])
        imNew.putpixel((10, 12), colorsDict["goldenVipers4"])
        imNew.putpixel((11, 12), colorsDict["goldenVipers5"])
        imNew.putpixel((12, 12), colorsDict["goldenVipers6"])
        imNew.putpixel((13, 12), colorsDict["goldenVipers5"])
        imNew.putpixel((14, 12), colorsDict["goldenVipers4"])
        imNew.putpixel((15, 12), colorsDict["goldenVipers3"])
        imNew.putpixel((16, 12), colorsDict["goldenVipers2"])
        imNew.putpixel((17, 12), colorsDict["goldenVipers1"])

        imNew.putpixel((8, 13), colorsDict["goldenVipers2"])
        imNew.putpixel((9, 13), colorsDict["goldenVipers3"])
        imNew.putpixel((10, 13), colorsDict["goldenVipers4"])
        imNew.putpixel((11, 13), colorsDict["goldenVipers5"])
        imNew.putpixel((13, 13), colorsDict["goldenVipers5"])
        imNew.putpixel((14, 13), colorsDict["goldenVipers4"])
        imNew.putpixel((15, 13), colorsDict["goldenVipers3"])
        imNew.putpixel((16, 13), colorsDict["goldenVipers2"])

    elif decodedType == "SolanaShades":

        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["solanaShades5"])
        imNew.putpixel((9, 11), colorsDict["solanaShades4"])
        imNew.putpixel((10, 11), colorsDict["solanaShades3"])
        imNew.putpixel((11, 11), colorsDict["solanaShades2"])
        imNew.putpixel((12, 11), colorsDict["solanaShades1"])
        imNew.putpixel((13, 11), colorsDict["solanaShades2"])
        imNew.putpixel((14, 11), colorsDict["solanaShades3"])
        imNew.putpixel((15, 11), colorsDict["solanaShades4"])
        imNew.putpixel((16, 11), colorsDict["solanaShades5"])
        imNew.putpixel((17, 11), colorsDict["solanaShades6"])

        imNew.putpixel((5, 12), colorsDict["black"])
        imNew.putpixel((6, 12), colorsDict["black"])
        imNew.putpixel((7, 12), colorsDict["solanaShades6"])
        imNew.putpixel((8, 12), colorsDict["solanaShades5"])
        imNew.putpixel((9, 12), colorsDict["solanaShades4"])
        imNew.putpixel((10, 12), colorsDict["solanaShades3"])
        imNew.putpixel((11, 12), colorsDict["solanaShades2"])
        imNew.putpixel((12, 12), colorsDict["solanaShades1"])
        imNew.putpixel((13, 12), colorsDict["solanaShades2"])
        imNew.putpixel((14, 12), colorsDict["solanaShades3"])
        imNew.putpixel((15, 12), colorsDict["solanaShades4"])
        imNew.putpixel((16, 12), colorsDict["solanaShades5"])
        imNew.putpixel((17, 12), colorsDict["solanaShades6"])

        imNew.putpixel((8, 13), colorsDict["solanaShades5"])
        imNew.putpixel((9, 13), colorsDict["solanaShades4"])
        imNew.putpixel((10, 13), colorsDict["solanaShades3"])
        imNew.putpixel((11, 13), colorsDict["solanaShades2"])
        imNew.putpixel((13, 13), colorsDict["solanaShades2"])
        imNew.putpixel((14, 13), colorsDict["solanaShades3"])
        imNew.putpixel((15, 13), colorsDict["solanaShades4"])
        imNew.putpixel((16, 13), colorsDict["solanaShades5"])

    elif decodedType == "LaserEyes":
        imNew.putpixel((8, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((9, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((10, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((11, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((12, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((13, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((14, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((15, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((16, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((17, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((18, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((19, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((20, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((21, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((22, 11), colorsDict["laserEyesOuter"])
        imNew.putpixel((23, 11), colorsDict["laserEyesOuter"])

        imNew.putpixel((7, 12), colorsDict["laserEyesOuter"])
        imNew.putpixel((8, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((9, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((10, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((11, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((12, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((13, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((14, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((15, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((16, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((17, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((18, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((19, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((20, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((21, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((22, 12), colorsDict["laserEyesInner"])
        imNew.putpixel((23, 12), colorsDict["laserEyesInner"])

        imNew.putpixel((8, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((9, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((10, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((11, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((12, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((13, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((14, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((15, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((16, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((17, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((18, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((19, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((20, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((21, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((22, 13), colorsDict["laserEyesOuter"])
        imNew.putpixel((23, 13), colorsDict["laserEyesOuter"])
    elif decodedType == "Solaneyes":
        imNew.putpixel((8, 12), colorsDict["solaneyesLeft"])
        imNew.putpixel((14, 12), colorsDict["solaneyesRight"])
    elif decodedType == "Monocle":
        imNew.putpixel((8, 11), colorsDict["monocleOutline"])
        imNew.putpixel((9, 11), colorsDict["monocleOutline"])

        imNew.putpixel((7, 12), colorsDict["monocleOutline"])
        imNew.putpixel((8, 12), colorsDict["monocle"])
        imNew.putpixel((9, 12), colorsDict["monocle"])
        imNew.putpixel((10, 12), colorsDict["monocleOutline"])

        imNew.putpixel((7, 13), colorsDict["monocleOutline"])
        imNew.putpixel((8, 13), colorsDict["monocle"])
        imNew.putpixel((9, 13), colorsDict["monocle"])
        imNew.putpixel((10, 13), colorsDict["monocleOutline"])

        imNew.putpixel((6, 14), colorsDict["monocleOutline"])
        imNew.putpixel((8, 14), colorsDict["monocleOutline"])
        imNew.putpixel((9, 14), colorsDict["monocleOutline"])

        imNew.putpixel((6, 15), colorsDict["monocleOutline"])

        imNew.putpixel((6, 16), colorsDict["monocleOutline"])

        imNew.putpixel((5, 17), colorsDict["monocleOutline"])

        imNew.putpixel((5, 18), colorsDict["monocleOutline"])

        imNew.putpixel((4, 19), colorsDict["monocleOutline"])
        imNew.putpixel((4, 20), colorsDict["monocleOutline"])
        imNew.putpixel((4, 21), colorsDict["monocleOutline"])
    elif decodedType == "Vice Shades":

        imNew.putpixel((5, 10), colorsDict["black"])
        imNew.putpixel((6, 10), colorsDict["black"])
        imNew.putpixel((7, 10), colorsDict["black"])
        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])
        imNew.putpixel((17, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["viceBrown"])
        imNew.putpixel((9, 11), colorsDict["viceBrown"])
        imNew.putpixel((10, 11), colorsDict["viceBrown"])
        imNew.putpixel((11, 11), colorsDict["viceBrown"])
        imNew.putpixel((12, 11), colorsDict["black"])
        imNew.putpixel((13, 11), colorsDict["viceBrown"])
        imNew.putpixel((14, 11), colorsDict["viceBrown"])
        imNew.putpixel((15, 11), colorsDict["viceBrown"])
        imNew.putpixel((16, 11), colorsDict["viceBrown"])
        imNew.putpixel((17, 11), colorsDict["black"])

        imNew.putpixel((7, 12), colorsDict["black"])
        imNew.putpixel((8, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((9, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((10, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((11, 12), colorsDict["black"])
        imNew.putpixel((13, 12), colorsDict["black"])
        imNew.putpixel((14, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((15, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((16, 12), colorsDict["viceBrownLight"])
        imNew.putpixel((17, 12), colorsDict["black"])

        imNew.putpixel((7, 13), colorsDict["black"])
        imNew.putpixel((8, 13), colorsDict["black"])
        imNew.putpixel((9, 13), colorsDict["black"])
        imNew.putpixel((10, 13), colorsDict["black"])
        imNew.putpixel((14, 13), colorsDict["black"])
        imNew.putpixel((15, 13), colorsDict["black"])
        imNew.putpixel((16, 13), colorsDict["black"])
        imNew.putpixel((17, 13), colorsDict["black"])

    elif decodedType == "NavyThugLyfe":

        imNew.putpixel((4, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((5, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((6, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((7, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((8, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((9, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((10, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((11, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((12, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((13, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((14, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((15, 10), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((16, 10), colorsDict["navyThugLyfeOutline"])

        imNew.putpixel((6, 11), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((7, 11), colorsDict["navyThugLyfe"])
        imNew.putpixel((8, 11), colorsDict["navyThugLyfe"])
        imNew.putpixel((9, 11), colorsDict["navyThugLyfe"])
        imNew.putpixel((10, 11), colorsDict["white"])
        imNew.putpixel((11, 11), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((12, 11), colorsDict["navyThugLyfe"])
        imNew.putpixel((13, 11), colorsDict["navyThugLyfe"])
        imNew.putpixel((14, 11), colorsDict["navyThugLyfe"])
        imNew.putpixel((15, 11), colorsDict["navyThugLyfe"])
        imNew.putpixel((16, 11), colorsDict["white"])
        imNew.putpixel((17, 11), colorsDict["navyThugLyfeOutline"])

        imNew.putpixel((7, 12), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((8, 12), colorsDict["navyThugLyfe"])
        imNew.putpixel((9, 12), colorsDict["white"])
        imNew.putpixel((10, 12), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((12, 12), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((13, 12), colorsDict["navyThugLyfe"])
        imNew.putpixel((14, 12), colorsDict["navyThugLyfe"])
        imNew.putpixel((15, 12), colorsDict["white"])
        imNew.putpixel((16, 12), colorsDict["navyThugLyfeOutline"])

        imNew.putpixel((8, 13), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((9, 13), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((13, 13), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((14, 13), colorsDict["navyThugLyfeOutline"])
        imNew.putpixel((15, 13), colorsDict["navyThugLyfeOutline"])
    elif decodedType == "ThugLyfe":

        imNew.putpixel((4, 10), colorsDict["black"])
        imNew.putpixel((5, 10), colorsDict["black"])
        imNew.putpixel((6, 10), colorsDict["black"])
        imNew.putpixel((7, 10), colorsDict["black"])
        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])
        imNew.putpixel((16, 10), colorsDict["black"])

        imNew.putpixel((6, 11), colorsDict["black"])
        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["black"])
        imNew.putpixel((9, 11), colorsDict["black"])
        imNew.putpixel((10, 11), colorsDict["white"])
        imNew.putpixel((11, 11), colorsDict["black"])
        imNew.putpixel((12, 11), colorsDict["black"])
        imNew.putpixel((13, 11), colorsDict["black"])
        imNew.putpixel((14, 11), colorsDict["black"])
        imNew.putpixel((15, 11), colorsDict["black"])
        imNew.putpixel((16, 11), colorsDict["white"])
        imNew.putpixel((17, 11), colorsDict["black"])

        imNew.putpixel((7, 12), colorsDict["black"])
        imNew.putpixel((8, 12), colorsDict["black"])
        imNew.putpixel((9, 12), colorsDict["white"])
        imNew.putpixel((10, 12), colorsDict["black"])
        imNew.putpixel((12, 12), colorsDict["black"])
        imNew.putpixel((13, 12), colorsDict["black"])
        imNew.putpixel((14, 12), colorsDict["black"])
        imNew.putpixel((15, 12), colorsDict["white"])
        imNew.putpixel((16, 12), colorsDict["black"])

        imNew.putpixel((8, 13), colorsDict["black"])
        imNew.putpixel((9, 13), colorsDict["black"])
        imNew.putpixel((13, 13), colorsDict["black"])
        imNew.putpixel((14, 13), colorsDict["black"])
        imNew.putpixel((15, 13), colorsDict["black"])

    elif decodedType == "Tear":
        imNew.putpixel((8, 14), colorsDict["tears"])
        # imNew.putpixel((9, 14), colorsDict["tears"])
        # imNew.putpixel((14, 14), colorsDict["tears"])
        # imNew.putpixel((15, 14), colorsDict["tears"])

        # imNew.putpixel((8, 15), colorsDict["tears"])
        # imNew.putpixel((15, 15), colorsDict["tears"])

        # imNew.putpixel((8, 17), colorsDict["tears"])
    elif decodedType == "ClassyGlasses":

        imNew.putpixel((7, 11), colorsDict["monocleOutline"])
        imNew.putpixel((8, 11), colorsDict["monocleOutline"])
        imNew.putpixel((9, 11), colorsDict["monocleOutline"])
        imNew.putpixel((10, 11), colorsDict["monocleOutline"])
        imNew.putpixel((11, 11), colorsDict["monocleOutline"])
        imNew.putpixel((12, 11), colorsDict["monocleOutline"])
        imNew.putpixel((13, 11), colorsDict["monocleOutline"])
        imNew.putpixel((14, 11), colorsDict["monocleOutline"])
        imNew.putpixel((15, 11), colorsDict["monocleOutline"])
        imNew.putpixel((16, 11), colorsDict["monocleOutline"])

        imNew.putpixel((6, 12), colorsDict["monocleOutline"])
        imNew.putpixel((7, 12), colorsDict["glasses"])
        imNew.putpixel((8, 12), colorsDict["glassesLight"])
        imNew.putpixel((9, 12), colorsDict["glasses"])
        imNew.putpixel((10, 12), colorsDict["glasses"])
        imNew.putpixel((13, 12), colorsDict["glasses"])
        imNew.putpixel((14, 12), colorsDict["glassesLight"])
        imNew.putpixel((15, 12), colorsDict["glasses"])
        imNew.putpixel((16, 12), colorsDict["glasses"])

        imNew.putpixel((7, 13), colorsDict["glassesLight"])
        imNew.putpixel((8, 13), colorsDict["glasses"])
        imNew.putpixel((9, 13), colorsDict["glasses"])
        imNew.putpixel((10, 13), colorsDict["glasses"])
        imNew.putpixel((13, 13), colorsDict["glassesLight"])
        imNew.putpixel((14, 13), colorsDict["glasses"])
        imNew.putpixel((15, 13), colorsDict["glasses"])
        imNew.putpixel((16, 13), colorsDict["glasses"])

        imNew.putpixel((7, 14), colorsDict["glasses"])
        imNew.putpixel((8, 14), colorsDict["glasses"])
        imNew.putpixel((9, 14), colorsDict["glasses"])
        imNew.putpixel((10, 14), colorsDict["glasses"])
        imNew.putpixel((13, 14), colorsDict["glasses"])
        imNew.putpixel((14, 14), colorsDict["glasses"])
        imNew.putpixel((15, 14), colorsDict["glasses"])
        imNew.putpixel((16, 14), colorsDict["glasses"])


    elif decodedType == "AngryEyebrows":

        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])

        imNew.putpixel((10, 11), colorsDict["black"])
        imNew.putpixel((13, 11), colorsDict["black"])

    elif decodedType == "HeartEyes":

        imNew.putpixel((8, 10), colorsDict["heartEyesRed"])
        imNew.putpixel((10, 10), colorsDict["heartEyesRed"])
        imNew.putpixel((13, 10), colorsDict["heartEyesRed"])
        imNew.putpixel((15, 10), colorsDict["heartEyesRed"])

        imNew.putpixel((7, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((8, 11), colorsDict["white"])
        imNew.putpixel((9, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((10, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((11, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((12, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((13, 11), colorsDict["white"])
        imNew.putpixel((14, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((15, 11), colorsDict["heartEyesRed"])
        imNew.putpixel((16, 11), colorsDict["heartEyesRed"])

        imNew.putpixel((7, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((8, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((9, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((10, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((11, 12), colorsDict["heartEyesRedShade"])
        imNew.putpixel((12, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((13, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((14, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((15, 12), colorsDict["heartEyesRed"])
        imNew.putpixel((16, 12), colorsDict["heartEyesRedShade"])

        imNew.putpixel((8, 13), colorsDict["heartEyesRed"])
        imNew.putpixel((9, 13), colorsDict["heartEyesRed"])
        imNew.putpixel((10, 13), colorsDict["heartEyesRedShade"])
        imNew.putpixel((13, 13), colorsDict["heartEyesRed"])
        imNew.putpixel((14, 13), colorsDict["heartEyesRed"])
        imNew.putpixel((15, 13), colorsDict["heartEyesRedShade"])

        imNew.putpixel((9, 14), colorsDict["heartEyesRedShade"])
        imNew.putpixel((14, 14), colorsDict["heartEyesRedShade"])

    elif decodedType == "Cyclops":

        imNew.putpixel((6, 10), colorsDict["black"])
        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((10, 10), colorsDict["black"])
        imNew.putpixel((11, 10), colorsDict["black"])
        imNew.putpixel((12, 10), colorsDict["black"])
        imNew.putpixel((13, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])

        imNew.putpixel((5, 11), colorsDict["black"])
        imNew.putpixel((6, 11), colorsDict["cyclopsYellowShade"])
        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["cyclopsYellowShade"])
        imNew.putpixel((9, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((10, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((11, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((12, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((13, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((14, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((15, 11), colorsDict["cyclopsYellow"])
        imNew.putpixel((16, 11), colorsDict["black"])

        imNew.putpixel((4, 12), colorsDict["black"])
        imNew.putpixel((5, 12), colorsDict["cyclopsYellowShade"])
        imNew.putpixel((6, 12), colorsDict["cyclopsYellow"])
        imNew.putpixel((7, 12), colorsDict["cyclopsYellow"])
        imNew.putpixel((8, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((9, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((10, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((11, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((12, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((13, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((14, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((15, 12), colorsDict["cyclopsRed"])
        imNew.putpixel((16, 12), colorsDict["cyclopsYellowShade"])
        imNew.putpixel((17, 12), colorsDict["black"])

        imNew.putpixel((5, 13), colorsDict["black"])
        imNew.putpixel((6, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((7, 13), colorsDict["black"])
        imNew.putpixel((8, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((9, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((10, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((11, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((12, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((13, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((14, 13), colorsDict["cyclopsYellow"])
        imNew.putpixel((15, 13), colorsDict["cyclopsYellowShade"])
        imNew.putpixel((16, 13), colorsDict["black"])

        imNew.putpixel((6, 14), colorsDict["black"])
        imNew.putpixel((8, 14), colorsDict["black"])
        imNew.putpixel((9, 14), colorsDict["black"])
        imNew.putpixel((10, 14), colorsDict["black"])
        imNew.putpixel((11, 14), colorsDict["black"])
        imNew.putpixel((12, 14), colorsDict["black"])
        imNew.putpixel((13, 14), colorsDict["black"])
        imNew.putpixel((14, 14), colorsDict["black"])
        imNew.putpixel((15, 14), colorsDict["black"])

    elif decodedType == "GoogleyEyes":

        imNew.putpixel((8, 10), colorsDict["black"])
        imNew.putpixel((9, 10), colorsDict["black"])
        imNew.putpixel((14, 10), colorsDict["black"])
        imNew.putpixel((15, 10), colorsDict["black"])

        imNew.putpixel((7, 11), colorsDict["black"])
        imNew.putpixel((8, 11), colorsDict["black"])
        imNew.putpixel((9, 11), colorsDict["white"])
        imNew.putpixel((10, 11), colorsDict["black"])
        imNew.putpixel((13, 11), colorsDict["black"])
        imNew.putpixel((14, 11), colorsDict["white"])
        imNew.putpixel((15, 11), colorsDict["white"])
        imNew.putpixel((16, 11), colorsDict["black"])

        imNew.putpixel((7, 12), colorsDict["black"])
        imNew.putpixel((8, 12), colorsDict["white"])
        imNew.putpixel((9, 12), colorsDict["white"])
        imNew.putpixel((10, 12), colorsDict["black"])
        imNew.putpixel((13, 12), colorsDict["black"])
        imNew.putpixel((14, 12), colorsDict["white"])
        imNew.putpixel((15, 12), colorsDict["black"])
        imNew.putpixel((16, 12), colorsDict["black"])

        imNew.putpixel((8, 13), colorsDict["black"])
        imNew.putpixel((9, 13), colorsDict["black"])
        imNew.putpixel((14, 13), colorsDict["black"])
        imNew.putpixel((15, 13), colorsDict["black"])

    im.paste(imNew, (0,0), mask=imNew)
